#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-git
Version  : 1.3.0
Release  : 7
URL      : https://rubygems.org/downloads/git-1.3.0.gem
Source0  : https://rubygems.org/downloads/git-1.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Git Library for Ruby
Library for using Git in Ruby.
## Homepage
Git public hosting of the project source code is at:

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n git-1.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-git.gemspec

%build
gem build rubygem-git.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
git-1.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/git-1.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/author.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base/factory.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/branch.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/branches.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/diff.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/index.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/log.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/path.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/remote.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/repository.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/stash.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/stashes.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/status.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/working_directory.rb
/usr/lib64/ruby/gems/2.3.0/specifications/git-1.3.0.gemspec
